version: '3.1'

services:
  api:
    user: node
    working_dir: /server
    hostname: ecommerce
    ports:
      - 8080:8080
    build:
      context: ./server
      dockerfile: Dockerfile
  nextjs:
    user: node
    working_dir: /client
    ports:
      - 3000:3000
    depends_on:
      - api
    environment:
      - REACT_APP_HOSTNAME=${REACT_APP_HOSTNAME:-ecommerce}
      - REACT_APP_HOST_PORT=${REACT_APP_HOST_PORT:-8080}
    build:
      context: ./client
      dockerfile: Dockerfile
    stdin_open: true
