version: '3.1'

volumes:
  application:
    name: application

services:
  api:
    working_dir: /node
    user: node
    volumes:
      - application:/node
    hostname: ecommerce
    ports:
      - 8080:8080
    build:
      context: .
      dockerfile: Dockerfile
    command: node generate.js && json-server --watch db.json --port=${REACT_APP_HOST_PORT:-8080} --host=0.0.0.0
  nextjs:
    working_dir: /node
    ports:
      - 3000:3000
    depends_on:
      - api
    user: node
    volumes:
      - application:/node
    environment:
      - REACT_APP_HOSTNAME=${REACT_APP_HOSTNAME:-ecommerce}
      - REACT_APP_HOST_PORT=${REACT_APP_HOST_PORT:-8080}
    build:
      context: .
    stdin_open: true
    command: npm run start
